export default {
  language: {
    name: "En"
  },
  navbar: {
    submit: "Submit",
    plan: "Incentive Plan"
  },
  footer: {
    homeName: "dApps",
    developer: {
      name: "Developer",
      center: "Developer Center",
      bounty: "Bounty Program",
      doc: "Documentation",
      github: "Github"
    },
    dApps: {
      name: "dApps",
      dl: "dApp Rankings",
      submit: "Submit a dApp"
    },
    business: {
      name: "Business",
      gaming: "Gaming Industry",
      creative: "Creative Industry"
    },
    trust: {
      name: "Trust Ecosystem",
      anchor: "Trust Anchor",
      node: "Node"
    },
    about: {
      name: "About",
      us: "About Us",
      res: "Resources",
      events: "Events",
      faq: "FAQ",
      whitePaper: "White Paper",
      explorer: "Explorer"
    }
  },
  main: {
    tl: {
      name: "dApp Rankings",
      total: {
        name: "dApp Total: ",
        txn: "24h Transactions: ",
        activeU: "24h Active Users: ",
        volume: "24h Volume: "
      },
      th: {
        dApp: "dApp",
        c: "Category",
        activeU: "Active users",
        txn: "Transactions",
        volume: "Volume",
        reward: "Weekly Reward (USD)",
        totalReward: "Total Reward (USD)"
      },
      td: {
        hour: "24h:",
        days: "7days:"
      }
    }
  },
  support: {
    index: {
      name: "“The Renaissance” Incentive Plan",
      detail1: {
        name: "Split the profits",
        nickname: "Early bird scheme",
        desc:
          "Receive an early bird offer of 60% dApp transaction fee rebate from April 1st, 2019! After three months, this number will be adjusted to 50%."
      },
      detail2: {
        name: "More active, More incentive",
        nickname: "Worker ant scheme",
        desc: "ONG reward for daily dApp rankings, ONT for weekly."
      },
      detail3: {
        name: "We pay for your development",
        nickname: "Angel investment scheme",
        desc:
          "For developers who start developing without funding, this program provides financial support right from the beginning."
      },
      detail4: {
        name: "Technical and marketing support for your dApps!",
        nickname: "Developer support scheme",
        desc: "We value ideas and help you realize them!"
      },
      detail: "Learn More"
    },
    breadcrumb: {
      home: "Home",
      plan: "Incentive plan",
      detail: "Incentive plan details"
    },
    example: "Example",
    detail: {
      submit: "Submit your dApp for incentives"
    },
    detail1: {
      tit:
        "“Early Bird Scheme”: Developers Receive 60% of the All Transaction Fees",
      txt1:
        "Each month developers will receive 50% of all the transaction fees (ONG) generated by dApps on the Ontology MainNet.",
      txt2:
        "Please note that in order to encourage those pioneering developers, we have set a 3-month “Early Bird Period”, which means 60% of all transaction fees generated by dApps will be returned to the dApp developer from April 1st, 2019 to June 30th, 2019.",
      txt3:
        "Let’s say Bob released a hit dApp through “Renaissance” incentive program on April 5th, 2019, and tens of thousands of users made transactions on the dApp. Bob will then receive 60% of the total transaction fees in the month of April, May, and June, and then 50% starting from July 1st.",
      txt4:
        "A note for all developers: The earlier you apply, the more you earn! Don’t miss out the “Early Bird Period”.",
      txt5:
        "Application review will take 1-2 business days, please apply as early as possible."
    },
    detail2: {
      tit: "“Worker Ant Scheme”: Extra Incentives for the Most Popular dApps",
      tit1: "Rules",
      tit2: "Requirements",
      tit3: "Incentive Rule",
      tit4: "Remember",
      txt1:
        "The most popular dApps will receive extra incentives. You can find the ranking on Ontology’s official dApp website: ",
      txt2: "https://dapp.ont.io/",
      txt3:
        "1. dApp ranking will be determined by the number of active users and transaction volume;",
      txt4:
        "2. The higher the ranking, the greater the incentive;",
      txt5:
        "3. Incentives will be given out in ONG.",
      txt6: "The dApp must have more than 100 daily active users (DAU) or its 24-hour transaction volume (VOL) must exceed 4,500 USD.",
      txt7: "Note: Data collection begins at 00:00 every Monday (UTC) and ends at 23:59 every Sunday (UTC). Daily active users refer to average weekly DAUs and daily transaction volume is the average daily transaction volume each week.",
      txt8:
        "If the number of qualified dApps in the ranking is under 20, the top 5 will share a prize pool of 20,000 USD in ONG each week based on their activity and daily transaction volume;",
      txt9: "If the number of qualified dApps in the ranking is between 20 and 50, the top 10 will share a prize pool of 50,000 USD in ONG each week based on their activity and daily transaction volume.",
      txt10:
        "Gambling dApps or dApps that falsify data are not included in this incentive model. We will disqualify any dApps whose activity is found to be manipulated.."
    },
    detail3: {
      tit: "Angel investment scheme",
      tit1: "Reduce the burden of operational cash flow",
      tit2: "Apply for the link",
      tit3: "How does the program work?",
      tit4: "Repayment plan of your choice",
      txt1:
        "Ontology encourages developers to jump start building their dApps on Ontology. For developers who start developing without funding, the loan program provides financial support right from the beginning.",
      txt2:
        "Developers can use the loan borrowed from the Ontology Foundation for their initial phase of dApp development, testing, and operation until it is up and running smoothly.",
      txt3: "Click here",
      txt4: "Standard loan program process (as pictured above)",
      txt5:
        "1st milestone: After you submit plans and functions of the dApp project, the Ontology Technical Committee will evaluate the materials and determine the loan amount, installment milestones, progress control, and repayment agreements between you and the developer team. The Ontology Technical Committee will appoint a project coordinator to track the progress of the project with your team.",
      txt6:
        "2nd milestone: When the dApp development is 70% complete, the Ontology Technical Committee will review it. After evaluating the project, we will issue the first installment of your loan.",
      txt7:
        "3rd milestone: After the dApp is launched, the second installment will be issued.",
      txt8:
        "4th milestone: When the loan is due, you will need to pay back your loan in the method you choose.",
      txt9: "",
      txt10:
        "The loan is issued in the form of ONT and we will record the equivalent USDT amount at the time of issuance (e.g. 10,000 ONT = 7,000 USDT). At the time of repayment, depending on the ONT price at the time, dApp developers can choose from two ways to pay back the loan:",
      txt11:
        "1) If the ONT price goes up developers can choose to return the equivalent USDT amount recorded at issuance.",
      txt12:
        "2)  If the ONT price goes down developers can choose to return the same amount of ONT. ",
      txt13: "* Gambling dApps are not included in this loan program.",
      url1: "https://goo.gl/forms/Jk8NQp0CD0ijuiLV2"
    },
    detail4: {
      tit: "Developer support scheme",
      tit1: "Apply for the link",
      txt1:
        "After providing developers with financial support for development and operation in Incentive Model A and B, we further hope to improve development efficiency and operational effectiveness through technical and marketing support.",
      txt2:
        "dApp developers can declare projects through the dApp page on our official website, and after the Technical department evaluates it, Ontology will assign a project owner to help develop and market the dApp throughout its life cycle.",
      txt3:
        "Developers who wish to participate in both the loan program and technical and market support must submit two applications to receive support for both.",
      txt4:
        "If you need technical & marketing support, please choose “Blockchain solutions inquiry” ",
      txt5: "here",
      txt6:
        ", and tell us what specific support you need in “Your message” area.",
      url1: "https://ont.io/#/dapp",
      url2: "https://ont.io/#/contactUs"
    }
  },
  tp: {
    tit: "Third Party dApp Stores"
  }
};
