export default {
  language: {
    name: "En"
  },
  navbar: {
    submit: "Submit",
    plan: "Incentive Plan"
  },
  footer: {
    homeName: "dApps",
    developer: {
      name: "Developer",
      center: "Developer Center",
      bounty: "Bounty Program",
      doc: "Documentation",
      github: "Github"
    },
    dApps: {
      name: "dApps",
      dl: "dApps List",
      submit: "Submit a dApp"
    },
    business: {
      name: "Business",
      gaming: "Gaming Industry",
      creative: "Creative Industry"
    },
    trust: {
      name: "Trust Ecosystem",
      anchor: "Trust Anchor",
      node: "Node"
    },
    about: {
      name: "About",
      us: "About Us",
      res: "Resources",
      events: "Events",
      faq: "FAQ",
      whitePaper: "White Paper",
      explorer: "Explorer"
    }
  },
  main: {
    tl: {
      name: "DApp List",
      total: {
        name: "Total:",
        txn: "24h Transaction:",
        activeU: "24h Active Users:",
        volume: "24h Volume:"
      },
      th: {
        dApp: "DApp",
        c: "Category",
        activeU: "Active user",
        txn: "Transactions",
        volume: "Volume",
        reward: "Reward"
      },
      td: {
        hour: "24h: ",
        days: "7day: "
      }
    }
  },
  support: {
    index: {
      name: "“The Renaissance” Incentive Plan",
      detail1: {
        name: "Split the Profits",
        nickname: "Big profits on nodes",
        desc:
          "Split the cost of the user's actions, 50% for developers and 50% for nodes."
      },
      detail2: {
        name: "Daily incentive and weekly incentive",
        nickname: "dApp Incentive Plan",
        desc: "ONT and ONG, the rewards for the top 50 activeness."
      },
      detail3: {
        name: "We pay for your development",
        nickname: "Loan Program",
        desc:
          "Without interest rate, we will help developers solving the problem of insufficient funds."
      },
      detail4: {
        name: "Asks for advice",
        nickname: "Developer Support",
        desc: "Ontology technical support team welcome your consultation."
      },
      detail: "Learn More"
    },
    breadcrumb: {
      home: "Home",
      plan: "Incentive plan",
      detail: "Incentive plan details"
    },
    example: "Example",
    detail1: {
      tit: "Transaction fee rebate",
      txt1:
        "50% of all transaction fees (ONG) generated by a dApp will be returned to the dApp developer. Ontology hopes this model will encourage intuitive and effective dApps.\n" +
        "We would now like to announce that during the first three months (April 1st to June 30th) we will be giving an early bird offer of 60% dApp transaction fee rebate to developers.\n",
      txt2:
        "A user makes a 0.01 ONG transaction on a developer’s dApp, this means 0.005 ONG is returned to the developer. As the dApp becomes more popular, the developer will get more and more ONG, and can generate an income from the transaction fee rebate along."
    },
    detail2: {
      tit: "Active dApp incentives",
      tit1: "Details of the plan include",
      tit2: "Revenue simulation curve",
      txt1: "The ",
      txt2: "Ontology Foundation",
      txt3:
        " has proposed an active dApp incentive model to rewarding dApps which rank in the top 50 in activity.",
      txt4: "",
      txt5: "1. Total incentive amount of 200,000,000 ONT and ONG",
      txt6:
        "The Ontology Foundation will award a total of 100,000,000 ONT and 100,000,000 ONG to the developers with the most active dApps in regular quotas.",
      txt7:
        "2. The incentive ranking is determined by dApp active users and transaction volume",
      txt8:
        "We will publicize the top 50 dApps based on the number of active users and transaction volume. If activity reaches a set number, it will qualify for ranking. If the number of dApps qualified for ranking is less than 50, the total bonus amount will be adjusted proportionally according to the number of dApps in the ranking.",
      txt9: "3. The higher the ranking, the greater the incentive",
      txt10:
        "Incentives are divided into daily and weekly incentive rankings. The daily rankings will use ONG as a reward, with a total daily incentive of 20,000 ONG per day. The weekly rankings will use ONT as a reward, with a total weekly incentive of 90,000 ONT. Higher rankings will receive greater incentives and if the same dApp appears in both daily and weekly rankings, it will receive both of the rewards.",
      txt11: "4. Incentive Model A declaration",
      txt12:
        "1） After one year of trial operation, the Foundation will determine whether to adjust the model based on community feedback.",
      txt13:
        "2） If dApp activity is found to be manipulated, a penalty will be issued.",
      txt14:
        "3） Gambling dApps are currently not included in this incentive model.",
      txt15: "",
      txt16:
        "If during a certain period of time the Ontology dApp Store had four dApps and only two applications qualify for the daily ranking and weekly ranking, the total daily reward will be 2/50 of 20,000 ONG and total weekly reward will be 2/50 of 90,000 ONT.\n" +
        "dApp D in the table below ranked second in the daily ranking, so would receive 263 ONG after the daily prize pool is reduced. Meanwhile, dApp D was ranked first in the weekly ranking, so 2,770 ONT from the weekly prize pool can be obtained. Therefore, the total income of dApp D for this period is 263 ONG and 2,770 ONT.\n",
      txt17:
        "As shown below, we simulated an expected revenue curve for the developer of a dApp. We hope the model will help dApp developers overcome early operation and maintenance difficulties, and provide enough incentives for dApp developers to maintain long-term operation when the user transaction volume has not yet reached the ideal profitable point."
    },
    detail3: {
      tit: "dApp development loan program",
      tit1: "Reduce the burden of operational cash flow",
      tit2: "Apply for the link",
      tit3: "How does the program work?",
      tit4: "Repayment plan of your choice",
      txt1:
        "Ontology encourages developers to jump start building their dApps on Ontology. For developers who start developing without funding, the loan program provides financial support right from the beginning.",
      txt2:
        "Developers can use the loan borrowed from the Ontology Foundation for their initial phase of dApp development, testing, and operation until it is up and running smoothly.",
      txt3: "https://goo.gl/forms/Jk8NQp0CD0ijuiLV2",
      txt4: "Standard loan program process (as pictured above)",
      txt5:
        "1st milestone: After you submit plans and functions of the dApp project, the Ontology Technical Committee will evaluate the materials and determine the loan amount, installment milestones, progress control, and repayment agreements between you and the developer team. The Ontology Technical Committee will appoint a project coordinator to track the progress of the project with your team.",
      txt6:
        "2nd milestone: When the dApp development is 70% complete, the Ontology Technical Committee will review it. After evaluating the project, we will issue the first installment of your loan.",
      txt7:
        "3rd milestone: After the dApp is launched, the second installment will be issued.",
      txt8:
        "4th milestone: When the loan is due, you will need to pay back your loan in the method you choose.",
      txt9: "",
      txt10:
        "The loan is issued in the form of ONT and we will record the equivalent USDT amount at the time of issuance (e.g. 10,000 ONT = 7,000 USDT). At the time of repayment, depending on the ONT price at the time, dApp developers can choose from two ways to pay back the loan:",
      txt11:
        "1) If the ONT price goes up developers can choose to return the equivalent USDT amount recorded at issuance.",
      txt12:
        "2)  If the ONT price goes down developers can choose to return the same amount of ONT. ",
      txt13: "* Gambling dApps are not included in this loan program."
    },
    detail4: {
      tit: "Technical and marketing support",
      tit1: "Apply for the link",
      txt1:
        "After providing developers with financial support for development and operation in Incentive Model A and B, we further hope to improve development efficiency and operational effectiveness through technical and marketing support.",
      txt2:
        "dApp developers can declare projects through the dApp page on our official website, and after the Technical department evaluates it, Ontology will assign a project owner to help develop and market the dApp throughout its life cycle.",
      txt3:
        "Developers who wish to participate in both the loan program and technical and market support must submit two applications to receive support for both.",
      txt4: "https://ont.io/#/dapp"
    }
  }
};
