export default {
  language: {
    name: "En"
  },
  navbar: {
    submit: "Submit",
    plan: "Incentive Plan"
  },
  footer: {
    homeName: "dApps",
    developer: {
      name: "Developer",
      center: "Developer Center",
      bounty: "Bounty Program",
      doc: "Documentation",
      github: "Github"
    },
    dApps: {
      name: "dApps",
      dl: "dApp Rankings",
      submit: "Submit a dApp"
    },
    business: {
      name: "Business",
      gaming: "Gaming Industry",
      creative: "Creative Industry"
    },
    trust: {
      name: "Trust Ecosystem",
      anchor: "Trust Anchor",
      node: "Node"
    },
    about: {
      name: "About",
      us: "About Us",
      res: "Resources",
      events: "Events",
      faq: "FAQ",
      whitePaper: "White Paper",
      explorer: "Explorer"
    }
  },
  alert: {
    chrome:
      "This page is only supported on the computer side using the Chrome browser to open."
  },
  message: {
    getCyanoInfoSuccess:
      "The ONT ID and Account Address have been successfully obtained.",
    bindWalletErr: "The ONT-ID and Wallet Address are already bound."
  },
  main: {
    tl: {
      name: "dApp Rankings",
      total: {
        name: "dApp Total: ",
        txn: "24h Transactions: ",
        activeU: "24h Active Users: ",
        volume: "24h Volume: "
      },
      th: {
        dApp: "dApp",
        c: "Category",
        activeU: "Active users",
        txn: "Transactions",
        volume: "Volume",
        reward: "Weekly Reward (USD)",
        totalReward: "Total Reward (USD)"
      },
      td: {
        hour: "24h:",
        days: "7days:"
      }
    },
    note:
      "Note: Data on 24-hour transaction and activity addresses from the previous day (UTC) is collected."
  },
  support: {
    index: {
      name: "“The Renaissance” Incentive Plan",
      bindBtn: {
        verify: {
          tit: "dApp binding verification",
          txt:
            "Account address binding and verification review for receiving incentives in participating in the incentive plan."
        },
        node: {
          tit: "dApp node binding",
          txt:
            "After the dApp binds the node, it can accept the node's fee redemption."
        },
        search: {
          tit: "Binding information query",
          txt: "Can query the results of binding verification and node binding"
        }
      },
      detail1: {
        name: "Split the profits",
        nickname: "Early bird scheme",
        desc:
          "Receive an early bird offer of 60% dApp transaction fee rebate from April 1st, 2019! After three months, this number will be adjusted to 50%."
      },
      detail2: {
        name: "More active, More incentive",
        nickname: "Worker ant scheme",
        desc: "ONG reward for daily dApp rankings, ONT for weekly."
      },
      detail3: {
        name: "We pay for your development",
        nickname: "Angel investment scheme",
        desc:
          "For developers who start developing without funding, this program provides financial support right from the beginning."
      },
      detail4: {
        name: "Technical and marketing support for your dApps!",
        nickname: "Developer support scheme",
        desc: "We value ideas and help you realize them!"
      },
      detail: "Learn More"
    },
    breadcrumb: {
      home: "Home",
      plan: "Incentive plan",
      detail: "Incentive plan details"
    },
    example: "Example",
    detail: {
      submit: "Submit your dApp for incentives"
    },
    detail1: {
      tit:
        "“Early Bird Scheme”: Developers receive 60% of all transaction fees",
      txt1:
        "Each month developers will receive 50% of all transaction fees (ONG) generated by dApps on the Ontology MainNet.",
      txt2:
        "In order to encourage pioneering developers, we have set a 3-month “Early Bird Period”, which means 60% of all transaction fees generated by dApps will be returned to the dApp developers from April 1st to June 30th, 2019.",
      txt3:
        "Let’s say a dApp developer released a hit dApp through Ontology on April 5th, 2019, and tens of thousands of users made transactions on the dApp. The developer will then receive 60% of all transaction fees in the month of April, May, and June, and then 50% starting from July 1st.",
      txt4:
        "A note for all developers: The earlier you apply, the more you earn! Don’t miss out.",
      txt5:
        "Application review will take 1-2 business days, please apply as early as possible."
    },
    detail2: {
      tit: "“Worker Ant Scheme”: Active dApp incentives",
      tit1: "Rules",
      tit2: "Requirements",
      tit3: "Incentive rules",
      tit4: "Remember",
      txt1:
        "The most popular dApps will receive extra incentives. You can find the ranking on Ontology’s official dApp website: ",
      txt2: "https://dapp.ont.io/",
      txt3:
        "1. dApp ranking will be determined by the number of active users and transaction volume;",
      txt4: "2. The higher the ranking, the greater the incentive;",
      txt5: "3. Incentives will be given out in ONG.",
      txt6:
        "The dApp must have more than 100 daily active users (DAU) or its 24-hour transaction volume (VOL) must exceed 4,500 USD.",
      txt7:
        "Note: Data collection begins at 00:00 every Monday (UTC) and ends at 23:59 every Sunday (UTC). Daily active users refer to average weekly DAUs and daily transaction volume is the average daily transaction volume each week.",
      txt8:
        "If the number of qualified dApps in the ranking is under 20, the top 5 will share a prize pool of 20,000 USD in ONG each week based on their activity and daily transaction volume;",
      txt9:
        "If the number of qualified dApps in the ranking is between 20 and 50, the top 10 will share a prize pool of 50,000 USD in ONG each week based on their activity and daily transaction volume.",
      txt10:
        "Gambling dApps or dApps that falsify data are not included in this incentive model. We will disqualify any dApps whose activity is found to be manipulated.."
    },
    detail3: {
      tit: "“Angel Investment Scheme”: dApp development loan program",
      txt1:
        "For developers who start developing without funding, Ontology launched a customized loan program. After the loan application is approved, Ontology will provide developers with financial support for development and operation, and allow them to repay the loans in the method they choose.",
      tit1: "How to apply:",
      txt2: "Send the following information to ",
      txt3: ":",
      txt4: "1. Team name;",
      txt5: "2. Team introduction;",
      txt6: "3. Contact person and phone number;",
      txt7: "4. The functions of your dApp;",
      txt8: "5. Estimated number of days needed for development;",
      txt9: "6. Estimated number of days needed for the loan;",
      txt10: "7. Estimated loan amount needed.",
      txt11: "Ontology will reply your email within 1-2 business days.",
      tit2: "Loan program process:",
      txt12:
        "Loan application -> Ontology Technical Committee evaluation (1-2 business days) -> Project owner assigned and loan amount determined -> Development phase -> Project owner assesses progress -> Progress review (at 70% completion) -> First installment -> dApp launch -> Second installment -> dApp live phase -> Regular progress update by applicant -> Loan repayment due",
      txt13: "1. Developers send their loan applications to ",
      txt14:
        "2. The Ontology Technical Committee evaluates applications and determines the loan amount;",
      txt15:
        "3. dApp enters development phase with support from Ontology throughout;",
      txt16:
        "4. When dApp development is 70% complete, the Ontology Technical Committee reviews it. After evaluating the project, we issue the first installment of your loan, which is 50% of the total loan amount;",
      txt17:
        "5. After the dApp is launched, the remaining 50% will be issued in the second installment;",
      txt18:
        "6. When the dApp is up and running and the loan is due, developers pay back their loans in the method they choose.",
      tit3: "Loan issuance:",
      txt19:
        "The loan is issued in ONT and we will record the equivalent USDT amount at the time of issuance.",
      tit4: "Repayment plan:",
      txt20:
        "At the time of repayment, depending on the ONT price at the time, dApp developers can choose from two ways to pay back the loan:",
      txt21:
        "1) Developers can choose to return the equivalent USDT amount recorded at issuance.",
      txt22: "2) Developers can choose to return the same amount of ONT.",
      txt23:
        "* Please Note: Gambling dApps or dApps that falsify data are not included in this incentive scheme. The copyright and operations of dApps belong to their developers.",
      email: "business@ont.io"
    },
    detail4: {
      tit:
        "Developer Support Scheme: Technical, marketing, and operation support",
      txt1:
        "In addition to financial support for development and operation, the Ontology team further provides developers with technical, marketing, and operation support.",
      tit1: "How to apply:",
      txt2: "Send the following information to ",
      txt3: ":",
      txt4: "1. Team name;",
      txt5: "2. Team introduction;",
      txt6: "3. Contact person and phone number;",
      txt7: "4. The functions of your dApp;",
      txt8: "5. Estimated number of days needed for development;",
      txt9: "Ontology will reply your email within 1-2 business days.",
      txt10:
        "After evaluating the application, Ontology will discuss with the dApp development team how to help market the dApp throughout its life cycle.",
      tit2: "Example",
      txt11: "HyperDragons Go! Launched on Ontology",
      txt12:
        "The gaming dApp HyperDragons Go! was officially launched on Ontology on December 25th, 2018. According to data on December 28th, the average daily growth rate of players in the first three days reached 272%, the average daily growth rate of active players was 919%, and the average daily growth rate of transactions was 756%.",
      txt13:
        "It only took the Ontology team five weeks to help move this game from Ethereum to Ontology. Our support in this process included:",
      tit3: "Technical support",
      txt14:
        "1. Providing protocols to help HyperDragons Go! to achieve the scan-to-play feature (ONTO is the first mobile app that supports such feature);",
      txt15: "2. Guidance on the use of the TS-SDK;",
      txt16: "3. Coding instructions and auditing of smart contracts.",
      tit4: "Marketing support",
      txt17:
        "1. Global community sharing: The news shared covered over 200,000 users over 36 channels on 11 social media platforms;",
      txt18:
        "2. Global marketing operations: event planning, poster design, news releases, community article writing and proofreading, real-time community maintenance, and feedback.",
      email: "marketing@ont.io"
    }
  },
  tp: {
    tit: "Third Party dApp Stores"
  },
  bind: {
    noIdentity:
      "There is no account (IDENTITY) in your Cyano Wallet, please login or create.",
    ruleMsg: {
      required: "This is required",
      length: "The length must be: "
    },
    verify: {
      tit: "DApp binding verification",
      txt:
        "DApp binding validation is available to developers. After the contract is successfully deployed, the developer will dApp and ONT ID (after the update operation is completed by the ONT ID), the dividend wallet (for dApp incentives), and the wallet binding for deploying the dApp.",
      txt2: {
        1: "Before binding, make sure you use the Chrome browser, install the cyano browser plugin and log in to the ONTID and the contract wallet address of your deployment. ",
        2: "Click to download the Cyano plugin"
      },
      ontId: "ONT ID:",
      scHash: "Contract Hash:",
      scAddress: "Deployment contract address:",
      scAddressDesc:
        "The administrator will verify that the deployment address is consistent with the actual deployment contract address. Please fill in correctly.",
      address: "Receiving an incentive address:",
      note:
        "Note: If you want to replace the receiving stimulus address, resubmit the binding verification information.",
      submit: "Submit",
      next: "Next",
      bindList: "The ONT ID has been bound to the address list: ",
      active: {
        tit1: "ONT ID binding wallet",
        tit2: "ONT ID binding dApp",
        tit3: "Waiting for administrator review"
      },
      confirmAlert: {
        tit: "dApp Binding Verification",
        txt: "Verification has been submitted successfully!",
        btn: "Confirm"
      },
      confirmQuit:
        "Your verification information has not been submitted to the administrator for review. After exiting the verification process, dApp binding verification is required. Confirm exit?"
    },
    node: {
      tit: "dApp node binding",
      txt:
        "Please complete the dApp binding verification before binding the node",
      scHash: "Contract Hash:",
      nodeName: "Node Name:",
      nodePublicKey: "Node Public Key:",
      note: "Note: The binding node can get the node fee sharing revenue.",
      submit: "Binding",
      placeholder: {
        nodeName: "Please select a node"
      },
      confirmAlert: {
        tit: "dApp Node Binding",
        txt: "The dApp node is successfully bound!",
        btn: "Confirm"
      },
      confirmGoToBind:
        "You have not completed the DAPP binding verification. Do you want to bind authentication?",
      confirmBinded:
        "You have completed the binding verification of the dApp. Confirm the binding node?"
    },
    search: {
      tit: "Binding information query",
      scHash: "Contract hash",
      submit: "Search",
      placeholder: {
        scHash: "Please enter the contract hash you are looking for."
      },
      result: {
        name: "Search Result",
        ontId: "ONT ID:",
        address: "Receiving the Incentive Address:",
        nodeName: "Binded Nodes:",
        nodePublicKey: "Node Public Key:"
      }
    }
  }
};
